### ISSUE TITLE
 ERROR (110): Error creating transaction - Request failed with status code 500

### ISSUE THREAD

**Issue by yanivgot** [itairaz1/israeli-bank-firefly-importer#136]
[2024-06-10 08:05:53.578] ERROR (110): Error creating transaction
    message: "Internal Firefly III Exception: bcadd(): Argument #1 ($num1) must be of type string, int given"
    tx: {
      "type": "withdrawal",
      "date": "2024-05-05T21:00:00.000Z",
      "amount": 1148.61,
      "description": "CONRAD AUH",
      "notes": "",
      "source_id": "30",
      "internal_reference": 369227170,
      "external_id": 369227170,
      "currency_code": "ILS",
      "process_date": "2024-07-01T21:00:00.000Z",
      "category_name": "שונות",
      "tags": [
        "30_2024-07-01T21:00:00.000Z"
      ]
    }
    error: {
      "message": "Request failed with status code 500",
      "name": "AxiosError",
      "stack":
          AxiosError: Request failed with status code 500
              at settle (file:///usr/local/lib/node_modules/israeli-bank-firefly-importer/node_modules/axios/lib/core/settle.js:19:12)
              at IncomingMessage.handleStreamEnd (file:///usr/local/lib/node_modules/israeli-bank-firefly-importer/node_modules/axios/lib/adapters/http.js:589:11)
              at IncomingMessage.emit (node:events:531:35)
              at endReadableNT (node:internal/streams/readable:1696:12)
              at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
              at Axios.request (file:///usr/local/lib/node_modules/israeli-bank-firefly-importer/node_modules/axios/lib/core/Axios.js:45:41)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async innerCreateTx (file:///usr/local/lib/node_modules/israeli-bank-firefly-importer/src/importer/index.js:285:5)
              at async doImport (file:///usr/local/lib/node_modules/israeli-bank-firefly-importer/src/importer/index.js:123:3)
              at async run (file:///usr/local/lib/node_modules/israeli-bank-firefly-importer/src/index.js:16:5)
              at async file:///usr/local/lib/node_modules/israeli-bank-firefly-importer/src/index.js:43:3
      "config": {
        "transitional": {
          "silentJSONParsing": true,
          "forcedJSONParsing": true,
          "clarifyTimeoutError": false
        },
        "adapter": [
          "xhr",
          "http",
          "fetch"
        ],
        "transformRequest": [
          null
        ],
        "transformResponse": [
          null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
          "Accept": "application/json, text/plain, */*",
          "Content-Type": "application/json",
          "Authorization": "[Redacted]",
          "User-Agent": "axios/1.7.2",
          "Content-Length": "333",
          "Accept-Encoding": "gzip, compress, deflate, br"
        },
        "baseURL": "http://homeassistant.local:3473",
        "method": "post",
        "url": "/api/v1/transactions",
        "data": "{\"transactions\":[{\"type\":\"withdrawal\",\"date\":\"2024-05-05T21:00:00.000Z\",\"amount\":1148.61,\"description\":\"CONRAD AUH\",\"notes\":\"\",\"source_id\":\"30\",\"internal_reference\":369227170,\"external_id\":369227170,\"currency_code\":\"ILS\",\"process_date\":\"2024-07-01T21:00:00.000Z\",\"category_name\":\"שונות\",\"tags\":[\"30_2024-07-01T21:00:00.000Z\"]}]}"
      },
      "code": "ERR_BAD_RESPONSE",
      "status": 500
    }

It's been several days since I've been unable to enter transactions from the credit card because of this error, can anyone help what the problem?

**Comment by itairaz1** [comment]
Hi Yaniv,
Which version of firefly do you use?
Try upgrade to the latest version

**Comment by itairaz1** [comment]
Just found that this bug was resolved in Firefly iii here https://github.com/firefly-iii/firefly-iii/issues/8907 and probably will be fix in the next version
I've tried to find a workaround, but couldn't, let's wait for this regression to be solved

**Comment by itairaz1** [comment]
6.1.17 with a fix was just released few minutes ago. Please let me know if it solved the issue

**Comment by Ovenlade** [comment]
I had the same error as in this issue and in issue 8907.

This was fixed in version 6.1.17 using the Home Assistant Add on.
After importing my balance in firefly was exactly the same as my 'real bank'. I imported 3,2 weeks of transactions. 

Very happy about it :)

**Comment by itairaz1** [comment]
Thanks, great to hear
It also solved for me
