### ISSUE TITLE
Request failed with status code 404 when trying to connect a local instance of fireflyiii

### ISSUE THREAD

**Issue by mickeyva** [itairaz1/israeli-bank-firefly-importer#46]
Hi
I installed fireflyiii locally on my debian server and keep getting "Request failed with status code 404" error.
I tried to reference my local firefly by ip and by http://localhost/ , gave the right token api in the config file and 404 is all I get...
`[2023-05-14 11:53:00.127] INFO (18460): Getting state from firefly...
[2023-05-14 11:53:00.178] ERROR (18460): Fatal error
    err: {
      "message": "Request failed with status code 404",
      "name": "AxiosError",
      "stack":
          AxiosError: Request failed with status code 404
              at settle (file:///usr/lib/node_modules/israeli-bank-firefly-importer/node_modules/axios/lib/core/settle.js:19:12)
              at IncomingMessage.handleStreamEnd (file:///usr/lib/node_modules/israeli-bank-firefly-importer/node_modules/axios/lib/adapters/http.js:570:11)
              at IncomingMessage.emit (node:events:525:35)
              at endReadableNT (node:internal/streams/readable:1359:12)
              at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

*EDIT*
After docker restart of fireflyiii I can now connect to firefly local instance but get the next error:
`Failed to launch the browser process!` 
So I ran the HOME ASSISTANT addon instead and the data retrieved very nice. 
I can verify the  israeli-bank-firefly-importer-hass-addon works well with Bank Hapoalim scraper.
`

**Comment by itairaz1** [comment]
Hi @mickeyva ,
I think you forgot to specify the port in the firefly url, the default port is 5432
